version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:16.10.0
      
jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Test target availability"
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_HOST 'echo test';
      - run: 
          name: "Install dependencies"
          command: |
            npm i;
      - run: 
          name: "Build app"
          command: |
            echo "REACT_APP_API_URL=$REACT_APP_API_URL" > .env;
            npm run build;
      - run: 
          name: "Deploy"
          command: |
            zip fe-build.zip -r .;
            chmod +x ./install.sh;
            scp -o StrictHostKeyChecking=no fe-build.zip $SSH_HOST:fe-build.zip;
            scp -o StrictHostKeyChecking=no install.sh $SSH_HOST:install.sh;
            ssh -o StrictHostKeyChecking=no $SSH_HOST './install.sh';
workflows:
  adventuremap-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
